### ISSUE TITLE
Java version planning

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretixscan-desktop#37]
Previously, pretixdesk was built for Java 9. Now, pretixdesk fails to build since there is no way to download Oracle JDK 9 right now since JDK 10 has been released. Additionally, using Java 9 has been a pain, since we needed to bundle it even for linux. 

It's not completely clear if we are in fact allowed to bundle Oracle JDK, therefore, we'd like to bundle OpenJDK. However, it's hard to get binary builds of OpenJDK that are compatible to JDK 9 or 10. Especially, with Java's 6-month-release schedule it's getting cumbersome for our small application to solve this problem anew every 6 months.

There are OpenJFX 8 builds [here](https://github.com/ojdkbuild/ojdkbuild). There are early-access builds for OpenJFX 10 [here](http://jdk.java.net/openjfx/) which are supposed to work with JDK 10 as well, but they're not supposed to be used in production.

Therefore, in #36, we're porting this back to Java 8 and use OpenJDK/OpenJFX. Java 8 will go out of service in late 2018 with the release of Java 11. The plan forward is, that as soon as Java 11 is released, we go straight from 8 to 11 and hope that we'll find a OpenJFX build for it, or use the EA ones.

**Comment by raphaelm** [comment]
I was unable to install OpenJFX on Travis for now, so we're still testing against Oracle JDK there.

**Comment by ZEROF** [comment]
Hi,

I try to buil *.jar on linux with oracle jdk 10.0.2, but build failed. Here you can find output:

https://paste.lugons.org/?011bdb011353e06a#Qb0OjDP2zgG7VC2WtuslLinl7qnXKwB4GVQIZawsa2Q=

Thanks

**Comment by raphaelm** [comment]
Somehow your missing JavaFX. However, have you read the above? We support JDK 8 only atm.

**Comment by ZEROF** [comment]
Ok, i will try to install V8, and see how things will go. Thanks

**Comment by ZEROF** [comment]
I got jdk 8, and I don't have same error now, but, I get this:

https://paste.lugons.org/?8c295619fe6c1659#OKm/wsLGzW2iCEMJSPZpE0Vht7/Vo/fiAIWrP9dtJII=

**Comment by johan12345** [comment]
It seems that the submodule with libpretixsync is missing. Have you used 
`git submodule update --init`
as described at https://github.com/pretix/pretixdesk#building-and-running?

**Comment by ZEROF** [comment]
I pulled repo again this morning when i installed JDK 10, didn't run submodule command. Thanks @johan12345

**Comment by raphaelm** [comment]
Please create a new issue if you have further problems instead of making this unrelated one hard to read ;)

**Comment by raphaelm** [comment]
Looks like we're not yet there, since tornadofx is not yet ported :( https://github.com/edvin/tornadofx/issues/817

**Comment by raphaelm** [comment]
Here's a really useful guide on packaging: https://medium.com/@adam_carroll/java-packager-with-jdk11-31b3d620f4a8
