### ISSUE TITLE
Error when selecting an event

### ISSUE THREAD

**Issue by thegcat** [pretix/pretixscan-desktop#47]
We have no clue why this happened, but after clicking the error away the program says "no check-in list", although the event has the standard check-in list and check-in-able items in this list.

<img width="709" alt="Bildschirmfoto 2019-08-05 um 15 53 16" src="https://user-images.githubusercontent.com/22835/62470766-6becb680-b79b-11e9-90b4-84afd511603b.png">

**Comment by raphaelm** [comment]
I have no idea either. Can you reproduce the error message?

**Comment by thegcat** [comment]
Sadly no. I'll keep my eyes peels if I see it again.
