### ISSUE TITLE
Misleading button "Disconnect from current event" in settings

### ISSUE THREAD

**Issue by b-schweiger** [pretix/pretixscan-desktop#48]
In the settings in the Windows app, there is a button captioned "Disconnect from current event" (see screenshot). However, this doesn't disconnect from an event, but from the organizer and it can't be reconnected without revoking the current device and creating a new one. Captioning the button correctly should help in preventing accidential disconnects. 
![image](https://user-images.githubusercontent.com/38404451/63893425-69702c00-c9ea-11e9-830c-9f698167d75b.png)

**Comment by raphaelm** [comment]
Has been fixed by now!
